### PR TITLE
Synthetic data models for benchmarking

### PR DESCRIPTION
**Pull request by KingMob**
This adds a namespace for generating synthetic data and models. It also adds some small QoL improvements to the main performance ns.

Future PRs in the stack:
1. Iterating over our first-pass parameter set
2. Automatically generating the queries from the synthetic data/models
3. Creating a command-line interface to run all this

Closes GDB-5

### CODE REVIEW

**Comment by Schaechtle** [comment]
This draft looks good to me.  Early on, we will want to vary the CRP alphas. So maybe make the following input to generate-db?
```clojure
(def ^:dynamic *default-local-alpha* 0.01)
(def ^:dynamic *default-global-alpha* 0.01)
```
One point that might be worth thinking about is what code can be re-used when all the random choices get exported from gen.clj traces in the future. The target format, i.e. ClojureCat is not expected to change soon.

Other than the above, the code strongly smells right for unblocking us for benchmarking. Note that I haven't done a line-by-line review yet.

**Comment by KingMob** [comment]
> This draft looks good to me. Early on, we will want to vary the CRP alphas. So maybe make the following input to generate-db?
> 
> ```clojure
> (def ^:dynamic *default-local-alpha* 0.01)
> (def ^:dynamic *default-global-alpha* 0.01)
> ```

These are just defaults. All three alpha values are override-able when calling `generate-db` (and the other `generate-*` fns. I named the keys categorical-alpha, local-alpha, and global-alpha, but lmk if there's better names.

> One point that might be worth thinking about is what code can be re-used when all the random choices get exported from gen.clj traces in the future. The target format, i.e. ClojureCat is not expected to change soon.

Do you mean, reuse gen.clj code to make random choices for the synthetic data/model? I agree that would be preferable in the long run.

**Comment by sritchie** [comment]
Checking if PR comments sync...

**Comment by KingMob** [comment]
Merging. Unclear what the nix-build problem is.

**Pull request merged**
